### ISSUE TITLE
Clicking topic should open the topic

### ISSUE THREAD

**Issue by briangormanly** [agorafoundation/agora#533]
<img width="417" alt="Screenshot 2023-12-23 at 8 30 56 AM" src="https://github.com/agorafoundation/agora/assets/2549569/5531bd12-4291-4a90-ac16-70117a5c441d">

This is actually a regression that was never fixed with the new front end. Right now, clicking on any part of a workspace in the dashboard opens the workspace to the first topic. When a user clicks on a particular topic in the workspace card as shown in the screenshot the editor should open and change the activeTopic to be the topic clicked.

**Comment by DenysLins** [comment]
Hey @briangormanly, can I work on that?

**Comment by briangormanly** [comment]
@DenysLins Absolutely appreciate the help. Let me know if you have any questions!

**Comment by DenysLins** [comment]
@briangormanly, please check if it is a valid solution

**Comment by briangormanly** [comment]
Merged and deployed in prod.
Thank you!
