### ISSUE TITLE
Need to add captcha

### ISSUE THREAD

**Issue by briangormanly** [agorafoundation/agora#537]
spam accounts have started coming in. One ironically spamming its captcha evading prowess. The accounts are being created with the standard account creation model, not Google SSO.

Keep in mind AI models like GPT vision and Apples new Ferret are likely changing the nature of this problem.

**Comment by A-4-Atom** [comment]
@briangormanly 
Hi, I'd like to fix it, can you help me a little? How do i go about adding a captcha. I've never done this before

**Comment by briangormanly** [comment]
Thank you!
I am actually thinking of trying a method first that just involves adding some fake fields to the sign-up form that are hidden html inputs.
Bots will try to fill them out, but humans won't see them and we can just look to see if any of our filled out and then disregard the user creation.

The common term used for this "honeypot fields". Probably best to use a field name that would be common on other forms, but we don't need.

The EJS file for the sign up form is here: client/agora/views/user-signup.ejs

We could check for the honeypot fields in the controller here: server/controller/userController.js

Let me know what you think.

**Comment by A-4-Atom** [comment]
@briangormanly I think we should first try honeypot fields, see if they're enough.
I forked the repo and got the project running locally. I've started working on it. If I have any questions or get stuck somewhere I'll let you know.

**Comment by briangormanly** [comment]
Completed. TY!
